### ISSUE TITLE
Error when using gulp#4.0

### ISSUE THREAD

**Issue by ngnijland** [doctyper/gulp-modernizr#45]
I use the following task:

```
// Modernizr
gulp.task('modernizr', function() {
    return gulp.src(
            [
                 'src/styles/**/*.sass',
                 'src/scripts/**/*.js'
            ]
        )
        .pipe(modernizr({
            cache : false,
            options: [
                'setClasses'
            ],
            tests: [
                'touchevents',
                'ellipsis',
                'flexbox',
                'flexboxlegacy',
                'csstransforms',
                'csstransitions',
                'cssanimations',
                'mediaqueries',
                'objectfit',
            ]
        }))
        .pipe(gulp.dest('dist/scripts'));
});
```

while using the following node and gulp versions:

```
node: v9.3.0
gulp: 4.0.0-alpha.3
gulp-cli: 2.0.0
```

When running the `modernizr` task I get the following error:

```
Error: premature close
    at Pumpify.onclose (/project/node_modules/end-of-stream/index.js:43:67)
    at Pumpify.emit (events.js:159:13)
    at Pumpify.Duplexify._destroy (/project/node_modules/duplexify/index.js:192:8)
    at /project/node_modules/duplexify/index.js:175:10
    at process._tickCallback (internal/process/next_tick.js:150:11)
```

Does anyone experience the same problem? It probably has something to do with using `gulp#4.0`. It works fine with `gulp#3.9.1`.

**Comment by bvdputte** [comment]
I'm experiencing the same:

```[15:39:02] Error: premature close
    at Pumpify.onclose (/Users/bart/projects/project/node_modules/end-of-stream/index.js:43:67)
    at emitNone (events.js:106:13)
    at Pumpify.emit (events.js:208:7)
    at Pumpify.Duplexify._destroy (/Users/bart/projects/project/node_modules/duplexify/index.js:192:8)
    at /Users/bart/projects/project/node_modules/duplexify/index.js:175:10
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)`

node: v8.9.3
gulp: 4.0.0-alpha.3
gulp-cli: 2.0.0

**Comment by rejas** [comment]
Same here with gulp4, gulp-cli 2.0.0 and node 9.3.0:
```
[11:00:42] 'prepare:modernizr' errored after 14 s
[11:00:42] Error: premature close
    at Pumpify.onclose (/Users/veeck/Projects/homepage/node_modules/end-of-stream/index.js:43:67)
    at Pumpify.emit (events.js:159:13)
    at Pumpify.Duplexify._destroy (/Users/veeck/Projects/homepage/node_modules/duplexify/index.js:192:8)
    at /Users/veeck/Projects/homepage/node_modules/duplexify/index.js:175:10
    at process._tickCallback (internal/process/next_tick.js:150:11)
```

**Comment by daniel-chapman-eqtr** [comment]
Same issue here:
```
[09:47:22] Error: premature close
    at Pumpify.onclose (D:\Webs\project\node_modules\end-of-stream\index.js:43:67)
    at emitNone (events.js:106:13)
    at Pumpify.emit (events.js:208:7)
    at Pumpify.Duplexify._destroy (D:\Webs\project\node_modules\duplexify\index.js:192:8)
    at D:\Webs\project\node_modules\duplexify\index.js:175:10
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

```
node: 8.9.3
npm: 5.5.1
gulp: 4.0.0
gulp-cli: 2.0.0
```

Tried the usual of deleting node_modules, clearing cache, etc.

**Comment by bvdputte** [comment]
FWIW, I've worked around this by not working with this "gulp-modernizr" (which seems to be a gulp wrapper around customizr anyway), as it seems abandoned?

```
var gulp = require('gulp'),
    customizr = require("customizr");

// Configfile
var config = {
    // More info: https://www.npmjs.com/package/customizr  or  https://github.com/Modernizr/customizr
    "cache" : true,
    "devFile" : false,
    "dest" : "dist/assets/modernizr/modernizr.js",
    "options" : [
        "setClasses"
    ],
    "uglify" : true,
    "tests" : [],
    "excludeTests": [],
    "crawl" : true,
    "useBuffers": false,
    "files" : {
        "src": [
            "src/assets/_scss/**/*.scss",
            "src/assets/js/*.js"
        ]
    },
    "customTests" : []
};

function modernizr(done) {
    customizr(config, function () {});
    done();
}

gulp.task(modernizr);
```

I hope this proves useful for anyone.

**Comment by rejas** [comment]
Fix is in develop branch
